using UnityEngine;

public class RoinStatesKit : MonoBehaviour
{
    public float speed,
                 speedRotation,
                 speedElongation;

    public bool allowRotation,
                allowMove;

    public Vector3 body_position,
                   arm0_position,
                   arm1_position,
                   arm2_position,
                   arm3_position,
                   arm4_position,
                   arm5_position,
                   arm6_position,
                   link1_position,
                   link2_position,
                   link3_position,
                   link4_position,
                   link5_position,
                   link6_position,
                   cylinder1_position,
                   cylinder2_position,
                   cylinder3_position,
                   cylinder5_position,
                   cylinder7_position,
                   piston1_position,
                   piston2_position,
                   piston3_position,
                   piston5_position,
                   piston7_position,
                   fixed3_position,
                   fixed5_position,
                   fixed7_position,
                   clutch5_position,
                   clutch7_position,
                   tong_position,

                   footFR_position,
                   cylinderFR_position,
                   pistonFR_position,
                   footFL_position,
                   cylinderFL_position,
                   pistonFL_position,
                   footBR_position,
                   cylinderBR_position,
                   pistonBR_position,
                   footBL_position,
                   cylinderBL_position,
                   pistonBL_position,

                   pitcher_position,
                   cylinderRoller_position,
                   roller_position,
                   yawer_position,
                   grip_position,
                   pistonRoller_position;

    public Quaternion body_rotation,
                       arm0_rotation,
                       arm1_rotation,
                       arm2_rotation,
                       arm3_rotation,
                       arm4_rotation,
                       arm5_rotation,
                       arm6_rotation,
                       link1_rotation,
                       link2_rotation,
                       link3_rotation,
                       link4_rotation,
                       link5_rotation,
                       link6_rotation,
                       cylinder1_rotation,
                       cylinder2_rotation,
                       cylinder3_rotation,
                       cylinder5_rotation,
                       cylinder7_rotation,
                       piston1_rotation,
                       piston2_rotation,
                       piston3_rotation,
                       piston5_rotation,
                       piston7_rotation,
                       fixed3_rotation,
                       fixed5_rotation,
                       fixed7_rotation,
                       clutch5_rotation,
                       clutch7_rotation,
                       tong_rotation,

                       footFR_rotation,
                       cylinderFR_rotation,
                       pistonFR_rotation,
                       footFL_rotation,
                       cylinderFL_rotation,
                       pistonFL_rotation,
                       footBR_rotation,
                       cylinderBR_rotation,
                       pistonBR_rotation,
                       footBL_rotation,
                       cylinderBL_rotation,
                       pistonBL_rotation,

                       pitcher_rotation,
                       cylinderRoller_rotation,
                       roller_rotation,
                       yawer_rotation,
                       grip_rotation,
                       pistonRoller_rotation;

    public float alpha0,
                alpha1, beta1, gamma1, d1, l1,
                alpha2, beta2, gamma2, d2, l2,
                alpha3, beta3, gamma3, d3, l3,
                alpha5, beta5, gamma5, phi5, psi51, psi52, theta5,
                l6,
                alphaPitch, beta7, gamma7, phi7, psi71, psi72, theta7,
                alphaFR, betaFR, gammaFR, dFR, lFR,
                alphaFL, betaFL, gammaFL, dFL, lFL,
                alphaBR, betaBR, gammaBR, dBR, lBR,
                alphaBL, betaBL, gammaBL, dBL, lBL,
                alphaRoll, betaRoll, gammaRoll, lRoll, dRoll,
                alphaYaw;
}
